### ISSUE TITLE
Add documentation related files

### ISSUE THREAD

**Issue by AdmiringWorm** [cake-contrib/Cake.Warp#1]
The files that need to be added:

- [ ] `.all-contributorsrc`
- [ ] `LICENSE`
- [ ] `CODE_OF_CONDUCT.md`
- [ ] `CONTRIBUTING.md`
- [ ] `README.md`
- [ ] `Issue Templates`
- [ ] `Pull Request Templates`

**Comment by gep13** [comment]
Are you using the CI/CD assets extension? 😄

**Comment by gep13** [comment]
What is the .all-contributors.rc file?

**Comment by gep13** [comment]
Never mind, now I know what it is! I need to add that to CI/CD assets 😄

**Comment by AdmiringWorm** [comment]
No, I am not using it.
I want to create my own set of templates to use first, then I probably will try my hands on creating a yeoman generator that can be re-used by others (to set up a Cake Addin repository).

**Comment by AdmiringWorm** [comment]
BTW, is the allcontributors bot set up for this repo?

**Comment by gep13** [comment]
I will have to check on that one. Let me get to my desk, and I will check how that is setup.
