### ISSUE TITLE
Add files related to building and tools we will use

### ISSUE THREAD

**Issue by AdmiringWorm** [cake-contrib/Cake.Warp#2]
The following tools need a configuration file(s)

- Cake
  - [x] Cake build script using Cake.Recipe
  - [x] Linux and OS X Bootstrapper
  - [x] Windows Bootstrapper
  - [x] Configuration file to pin cake version to `0.32.1`
- [x] codecov
- [x] `GitVersion` (Not Really needed, but good to have the ability to change it)
- [x] `GitReleaseManager`
- VSCode
  - [x] Task configuration to automatically re-run unit tests
  - [x] Configuration of file encoding (not supported by editorconfig yet)
- Git
  - [x] .gitignore
  - [x] .gitattributes
- CI
  - [x] .travis.yml
  - [x] .appveyor.yml
- [x] Mergify
- [x] editorconfig

I think that is all

**Comment by gep13** [comment]
What about:

* .editorconfig

There would also be dependabot and mergidy configuration files, but perhaps they are not required as they can be controlled through UI?

**Comment by AdmiringWorm** [comment]
I would prefer to have dependabot controlled through the UI (as there are more options available that way).

I forgot about mergify (it can't be controlled through theUI).
Thanks

**Comment by AdmiringWorm** [comment]
All configurations have been added.
Could be I will set up wyam in the future, but no plans right now
