### ISSUE TITLE
Embedd the warp binaries and extract the correct binary when the library gets loaded

### ISSUE THREAD

**Issue by AdmiringWorm** [cake-contrib/Cake.Warp#4]
This is possible to do by using one of the Fody Weavers, and would allow the addin to not have any external dependencies (Which would be the best as there is currently no installation for Warp, only download and execute(

**Comment by gep13** [comment]
I will be curious to see how you implement this!

**Comment by AdmiringWorm** [comment]
I was testing something of that sort yesterday, and got something.
But want to finish up all the configurations before I commit that code.

I will open it as a PR so you can have a look at it. Although the code for that is simple, I believe it would be best with a second pair of eyes to make sure.

**Comment by gep13** [comment]
Sure thing!  Keep me posted, in case I miss a notification.

**Comment by AdmiringWorm** [comment]
Implemented in https://github.com/cake-contrib/Cake.Warp/commit/fc658a00ca86a4366a0ef504d93aaba841763e9a
